version: '3.7'
services:
  db:
    image: postgres
  web:
    build: .
    command: python /code/manage.py runserver 
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
     - web-variables.env
volumes:
  postgres_data:
